import NavbarComponent from '@/components/navbar'
import axios from 'axios'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react' 
import { Carousel } from 'react-bootstrap'  
import Head from 'next/head'
function Garage() {
  const [Apartment, setApartment] = useState({})
  const [Structure, setStructure] = useState([])
  const [Carrousel, setCarrousel] = useState([])
  const router = useRouter()

  useEffect(() => {
    const fetchData = async () => {
      return await axios.get(
        `https://testing.tvikonekretnine.com/api/garageDetails.php?id=${router.query.id}`
      ) 
   
    }

    try {
      fetchData().then(async (res) => {

        console.log(res)
        console.log(res.data)
        let app = res.data[0]
        setStructure(res.data[0].structure)
        setApartment(app)  
        let array = app.other_images? app.other_images : [app.main_image]
        console.log(array)
        array.push(app.main_image) 
        setCarrousel(array.reverse())
        console.log(Carrousel)
      })
    } catch (error) {
      console.warn(error)
    }
   


  }, [router.query.id])

  return (
    
    <>
          <Head>
        <title>Real Estate </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
<script async src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous" />
<script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400&display=swap"
          rel="stylesheet"
        />
        <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
  integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
  crossorigin="anonymous"
/>
      </Head>
      <NavbarComponent/>
    
    <div> 
      <div className="background-section">
        <h1 style={{fontSize:"1.5em", fontWeight:700}} >Neka vaša potraga za savršenim domom bude jednostavna i ugodna.</h1>
      </div>
      <div className="container">
        <div className="ad-info-wrapper">
          <div className="gallery">
        {/*     <img
              src={`https://testing.tvikonekretnine.com/${Apartment.main_image}`}
              alt="gallery"
              style={{ height: '100%', width: '100%' }}
            /> */}
<Carousel slide={false} nextLabel='' prevLabel=''>
  {Carrousel.map((el, key) => (
    <Carousel.Item key={key}>
      <img
        className="img-fluid"
        onClick={() => {alert('lightbox not completed yet!')}}
        src={`https://testing.tvikonekretnine.com/${el}`}
        alt={`Slide ${key}`}
      />
    </Carousel.Item>
  ))}
</Carousel>
          </div>
          <div className="info-part">
            <h3 className="squarefeet">{Apartment.squarefeet}</h3>
            {Structure && Structure.length > 0 && Structure.map((el) => {
             
             if(el.value !== ""){
              return (
                <div className="icon-info" key={el.id}>
                  <img
                    src={`https://testing.tvikonekretnine.com/${el.icon}`}
                    width={64}
                    height={64}
                    alt="icon"
                    className="icon"
                  />
                  <div className="info">{el.value}</div>
                </div>
              )
             }
             
       
            })}
          </div>
        </div>

        <div className="ad-description">
          <h2>OPIS:</h2>
          <p className="ad-des">{Apartment.description} </p>
        </div>

        <div className="contact-info">
          <div className="phone">
            <h2 className="ph-h">KONTAKT TELEFON:</h2>
            <h2 className="number">+387 55 213 350</h2>
            <h2 className="number">+387 65 513 720</h2>
          </div>

          <div className="socials">
            <h2 className="ph-h">DRUŠTVENE MREŽE:</h2>
            <div className="soc-icons">
              <a href="">
                <img src="assets/instagram.png" alt="insta" />
              </a>
 

            <a href="">

              <img src="assets/facebook.png" alt="fb"/>
            </a>
            <a href="">

              <img src="assets/tik-tok.png" alt="tik tok"/>
            </a>

            <a href="">
              <img src="assets/youtube.png" alt="yt"/>

            </a>
          </div>
        </div>
      </div>

      <div className="see-more">
        <h2 className="more-h">POGLEDAJTE VIŠE NEKRETNINA</h2>
        <button className="more-btn"><div className="text-btn">POGLEDAJTE JOŠ</div><img src="assets/play.png" alt="play btn" className="more-em"/></button>
      </div>
    </div>
    </div>
    </>
  )
}

export default Garage